---
- hosts: all
  become: true
  tasks:
  
  - name: install packages
    yum:
      name:
        - traceroute
        - tcpdump
        - net-tools
        - wget
      state: present

 
- hosts: webserver
  become: true
  strategy: free
  tasks:
      
  - name: copy local_index.html to web server
    copy:
      src: local_index.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644
